#!/usr/bin/env python3
# Generates assets/ui/skin_theme_<faction>.tres, one per faction's deck.
#
# The theme is a build product of data/palette.json, not a hand edited file.
# That is what makes a skin swap the one file change CLAUDE.md 3.1 asks for:
# edit ui_factions, run scripts/gen-skin.sh, and the plates repaint and the
# themes rewrite themselves. A hand edited theme would carry the old skin's
# font colours and quietly disagree with the new plates.
#
# One theme per faction rather than one theme with a switch in it, because a
# Godot Theme is a resource rather than a program: there is nowhere in it to
# put a condition. The screen root swaps which resource it holds, which is one
# assignment, and every control under it repaints from the new one.
#
# A Godot Theme is CLAUDE.md 5.4's second case, a resource the engine genuinely
# requires: there is no other way to hand a StyleBox to every PanelContainer.
# It carries no gameplay, and every colour in it is resolved from the palette
# file here rather than typed.
#
# Nine patch margins come from tools/gen_ui_plates.py MARGINS, so the painter
# and the theme cannot drift about where a plate's stretchable middle begins.
#
# Usage: python3 tools/gen_theme.py   (or scripts/gen-skin.sh, which runs both)

import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from gen_ui_plates import B, MARGINS, PALETTE, faction_skins  # noqa: E402

UI_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "ui")
SKIN_DIR = "res://assets/ui/skin/"
FONT = "res://assets/ui/font_tactical.fnt"

# Content margins in device pixels: how far inside a plate its contents sit.
# The plate's frame is 4 blocks, so anything under 9 would put text on bronze
# rather than on the glass well the frame surrounds.
# Content margins, in the 1920x1080 design space. These are LAYOUT and scale
# with the reference resolution. The nine patch texture margins beside them do
# not: those describe art baked at B = 2 blocks, and 1.2 times 2 is not a whole
# number of pixels, so scaling them would resample pixel art at 1.25 and soften
# every border the skin has. Content margin is layout, texture margin is art.
PLATE_CONTENT = (12, 6, 12, 6)
HEADER_CONTENT = (17, 2, 17, 2)
BUTTON_CONTENT = (10, 5, 10, 5)


def rgb_of(name, colors, ui_colors):
    """A colour by name from either pool, as a Godot Color literal."""
    pool = dict(colors)
    pool.update(ui_colors)
    assert name in pool, "unknown colour %r" % (name,)
    t = pool[name].lstrip("#")
    return "Color(%s, %s, %s, 1)" % tuple(
        round(int(t[i:i + 2], 16) / 255.0, 3) for i in (0, 2, 4))


def stylebox(sid, texture, margins, content):
    m = [v * B for v in margins]
    return "\n".join([
        '[sub_resource type="StyleBoxTexture" id="%s"]' % sid,
        'texture = ExtResource("%s")' % texture,
        "texture_margin_left = %.1f" % m[0],
        "texture_margin_top = %.1f" % m[1],
        "texture_margin_right = %.1f" % m[2],
        "texture_margin_bottom = %.1f" % m[3],
        "content_margin_left = %.1f" % content[0],
        "content_margin_top = %.1f" % content[1],
        "content_margin_right = %.1f" % content[2],
        "content_margin_bottom = %.1f" % content[3],
    ])


def theme(faction, name, skin, data):
    """One faction's theme, as the text of a .tres."""
    colors, ui_colors = data["colors"], data["ui_colors"]
    lit = skin["lit"]
    chassis = skin["chassis"]

    def lit_of(role):
        return rgb_of(lit[role], colors, ui_colors)

    def chassis_of(role):
        return rgb_of(chassis[role], colors, ui_colors)

    textures = ["plate", "header", "button_normal", "button_hover",
                "button_pressed", "button_disabled"]
    ext = [('[ext_resource type="FontFile" path="%s" id="font"]' % FONT)]
    for t in textures:
        ext.append('[ext_resource type="Texture2D" path="%s%s/%s.png" id="%s"]'
                   % (SKIN_DIR, faction, t, t))

    boxes = [
        stylebox("plate", "plate", MARGINS["plate"], PLATE_CONTENT)
        + "\naxis_stretch_horizontal = 1\naxis_stretch_vertical = 1",
        stylebox("header", "header", MARGINS["header"], HEADER_CONTENT),
    ]
    for t in textures[2:]:
        boxes.append(stylebox(t, t, MARGINS[t], BUTTON_CONTENT))

    # The replay scrub, the one slider the rules allow (CLAUDE.md 6.2: nobody
    # reviewing a recording is under fire). Flat, because a nine patch groove
    # at this height would be all border and no groove.
    boxes.append("\n".join([
        '[sub_resource type="StyleBoxFlat" id="slider"]',
        "bg_color = %s" % lit_of("panel"),
        "content_margin_top = 3.0",
        "content_margin_bottom = 3.0",
    ]))
    boxes.append("\n".join([
        '[sub_resource type="StyleBoxFlat" id="grabber"]',
        "bg_color = %s" % lit_of("ok"),
        "content_margin_left = 4.0",
        "content_margin_right = 4.0",
    ]))

    head = "\n".join([
        "; GENERATED by tools/gen_theme.py: the %s deck, which is the %r skin" % (
            faction, name),
        "; in data/palette.json. Do not edit: change ui_factions or the skin's",
        "; role maps there and run scripts/gen-skin.sh, which repaints the",
        "; plates and rewrites this file. %s" % skin.get("note", ""),
        ";",
        "; Nine patch margins come from gen_ui_plates.MARGINS, so the painter",
        "; and this file cannot disagree about a plate's stretchable middle.",
    ])

    body = [
        "[resource]",
        "default_font = ExtResource(\"font\")",
        "default_font_size = 17",
        "Button/colors/font_color = %s" % chassis_of("label"),
        "Button/colors/font_hover_color = %s" % lit_of("fg"),
        "Button/colors/font_pressed_color = %s" % lit_of("ok"),
        "Button/colors/font_disabled_color = %s" % chassis_of("label_disabled"),
        "Button/colors/font_outline_color = %s" % chassis_of("head_shadow"),
        "Button/constants/outline_size = 2",
        'Button/styles/normal = SubResource("button_normal")',
        'Button/styles/hover = SubResource("button_hover")',
        'Button/styles/pressed = SubResource("button_pressed")',
        'Button/styles/disabled = SubResource("button_disabled")',
        'Button/styles/focus = SubResource("button_hover")',
        "CheckButton/colors/font_color = %s" % chassis_of("label"),
        'HSlider/styles/slider = SubResource("slider")',
        'HSlider/styles/grabber_area = SubResource("grabber")',
        'HSlider/styles/grabber_area_highlight = SubResource("grabber")',
        "Label/colors/font_color = %s" % lit_of("fg"),
        'HeaderLabel/base_type = &"Label"',
        'HeaderLabel/styles/normal = SubResource("header")',
        "HeaderLabel/colors/font_color = %s" % chassis_of("head_text"),
        "HeaderLabel/colors/font_outline_color = %s" % chassis_of("head_shadow"),
        "HeaderLabel/constants/outline_size = 2",
        "OptionButton/colors/font_color = %s" % chassis_of("label"),
        'OptionButton/styles/normal = SubResource("button_normal")',
        'OptionButton/styles/hover = SubResource("button_hover")',
        'OptionButton/styles/pressed = SubResource("button_pressed")',
        'OptionButton/styles/focus = SubResource("button_hover")',
        'Panel/styles/panel = SubResource("plate")',
        'PanelContainer/styles/panel = SubResource("plate")',
        "ProgressBar/colors/font_color = %s" % lit_of("dim"),
        "RichTextLabel/colors/default_color = %s" % lit_of("dim"),
    ]

    return "\n\n".join([
        "[gd_resource type=\"Theme\" load_steps=%d format=3]" % (
            len(ext) + len(boxes) + 1),
        head,
        "\n".join(ext),
        "\n\n".join(boxes),
        "\n".join(body),
    ]) + "\n"


def main():
    decks, data = faction_skins()
    for faction in sorted(decks):
        name, skin = decks[faction]
        out = os.path.join(UI_DIR, "skin_theme_%s.tres" % faction)
        with open(out, "w") as f:
            f.write(theme(faction, name, skin, data))
        print("wrote skin_theme_%s.tres  (skin: %s)" % (faction, name))


if __name__ == "__main__":
    main()
