#!/usr/bin/env python3
# Generates the committed placeholder meshes in assets/meshes/.
#
# Per CLAUDE.md section 2, a script may generate a model but its output must be
# a written .obj or .gltf file on disk, committed, never geometry built at
# runtime. Run this, then commit the .obj files it writes. The Godot import of
# those files is a build product.
#
# Every overlay mesh is a UNIT shape pointing at bearing 000 (+Z). Code never
# generates geometry; it only instances these files, rotates them in 30 degree
# steps, and scales them (CLAUDE.md section 5.1, placement only).
#
# Winding: every triangle's cross product agrees with its declared normal,
# the convention every DCC tool writes and the one shared with shiplib.slab.
# Anything else shades inside out in Godot: the fitting screen's directional
# light proved it on the frigate, going from black to lit the moment the
# winding matched the normals.
#
# Usage: python3 tools/gen_meshes.py

import math
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "meshes")


class Obj:
    def __init__(self):
        self.v = []
        self.vn = []
        self.f = []

    def vert(self, x, y, z):
        self.v.append((x, y, z))
        return len(self.v)

    def normal(self, x, y, z):
        self.vn.append((x, y, z))
        return len(self.vn)

    def tri(self, a, b, c, n):
        self.f.append(((a, n), (b, n), (c, n)))

    def write(self, name, comment):
        path = os.path.join(OUT, name)
        with open(path, "w") as f:
            f.write("# %s\n# Generated by tools/gen_meshes.py. Edit the script, not this file.\n" % comment)
            for v in self.v:
                f.write("v %.6f %.6f %.6f\n" % v)
            for n in self.vn:
                f.write("vn %.6f %.6f %.6f\n" % n)
            for face in self.f:
                f.write("f %d//%d %d//%d %d//%d\n" % (
                    face[0][0], face[0][1], face[1][0], face[1][1], face[2][0], face[2][1]))
        print("wrote %s  (%d verts, %d tris)" % (name, len(self.v), len(self.f)))


def bearing_xz(deg, r):
    # Bearing 0 is +Z, increasing clockwise when seen from above, matching the
    # simulation's atan2(x, z) convention and Godot's rotate_y.
    rad = math.radians(deg)
    return (math.sin(rad) * r, math.cos(rad) * r)


def flat_fan(o, deg_from, deg_to, radius, steps, y=0.0):
    # A pie slice on the XZ plane with an up normal, apex at the origin.
    n = o.normal(0, 1, 0)
    center = o.vert(0, y, 0)
    ring = []
    for i in range(steps + 1):
        d = deg_from + (deg_to - deg_from) * i / steps
        x, z = bearing_xz(d, radius)
        ring.append(o.vert(x, y, z))
    for i in range(steps):
        # Wound so the triangle cross product points up, with the normal.
        o.tri(center, ring[i], ring[i + 1], n)


def flat_band(o, deg_from, deg_to, r0, r1, steps, y=0.0):
    n = o.normal(0, 1, 0)
    inner = []
    outer = []
    for i in range(steps + 1):
        d = deg_from + (deg_to - deg_from) * i / steps
        xi, zi = bearing_xz(d, r0)
        xo, zo = bearing_xz(d, r1)
        inner.append(o.vert(xi, y, zi))
        outer.append(o.vert(xo, y, zo))
    for i in range(steps):
        o.tri(inner[i], outer[i], outer[i + 1], n)
        o.tri(inner[i], outer[i + 1], inner[i + 1], n)


def wedge30():
    o = Obj()
    flat_fan(o, -15, 15, 1.0, 6)
    o.write("wedge30.obj", "Unit 30 degree arc wedge, one sector of the 12 sector wheel")


def arc_segment():
    o = Obj()
    # One shield facing spans 60 degrees; a 4 degree gap at each end keeps six
    # instanced segments reading as six, matching the approved mockup.
    flat_band(o, -26, 26, 0.82, 1.0, 10)
    o.write("arc_seg.obj", "Unit shield facing band, 52 of 60 degrees")


def arc_glow():
    o = Obj()
    # The impact flare behind a shield facing. Deliberately WIDER than the 60
    # degrees a facing owns and than the arc_seg that reads it: at 88 degrees
    # each flare spills 14 degrees into both neighbours, so two facings hit at
    # once blend into one lobe instead of butting up as two bands. The shader
    # fades it out toward the ends, so the overlap adds gently rather than
    # showing a seam. Radially deeper than arc_seg for the same reason.
    flat_band(o, -44, 44, 0.66, 1.12, 18)
    o.write("arc_glow.obj", "Unit shield impact flare, 88 degrees, wider than one facing")


def turn_arc():
    o = Obj()
    # A FULL circle, because the turn it shows is any angle from nothing to a
    # half turn and a mesh cannot change its angular span. The shader masks it
    # down to the arc actually being swept (assets/shaders/turn_arc.gdshader),
    # which keeps one committed mesh instead of a family of fixed wedges or
    # geometry built at runtime.
    flat_band(o, 0, 360, 0.90, 1.0, 120)
    o.write("turn_arc.obj", "Unit band for the helm turn arc, masked by angle in the shader")


def ring():
    o = Obj()
    flat_band(o, 0, 360, 0.982, 1.0, 96)
    o.write("ring.obj", "Unit range ring band")


def quad():
    o = Obj()
    n = o.normal(0, 1, 0)
    a = o.vert(-0.5, 0, -0.5)
    b = o.vert(0.5, 0, -0.5)
    c = o.vert(0.5, 0, 0.5)
    d = o.vert(-0.5, 0, 0.5)
    o.tri(a, c, b, n)
    o.tri(a, d, c, n)
    o.write("quad.obj", "Unit XZ quad, centered, used for the grid plane")


def beam():
    o = Obj()
    n = o.normal(0, 1, 0)
    w = 0.5
    a = o.vert(-w, 0, 0)
    b = o.vert(w, 0, 0)
    c = o.vert(w, 0, 1)
    d = o.vert(-w, 0, 1)
    o.tri(a, c, b, n)
    o.tri(a, d, c, n)
    o.write("beam.obj", "Unit beam quad from origin to +Z, scaled to length and width in code")



# ---- solid building blocks ---------------------------------------------------
#
# The two ship hulls below are assembled from these. They are still authored
# geometry: this script writes .obj files to disk which are committed and
# imported, and nothing here runs at play time (CLAUDE.md sections 2 and 5.1).


def extrude(o, outline, y0, y1, cap=True):
    """Extrude an XZ polygon between two heights. Outline is convex, or at
    least fannable from its first vertex, and wound clockwise seen from above."""
    top = [o.vert(x, y1, z) for (x, z) in outline]
    bot = [o.vert(x, y0, z) for (x, z) in outline]
    if cap:
        up = o.normal(0, 1, 0)
        down = o.normal(0, -1, 0)
        for i in range(1, len(outline) - 1):
            # A fan over a slightly concave outline flips some triangles, so
            # wind each one from its own signed area to keep the cross with
            # the cap normal.
            (x0, z0) = outline[0]
            (xi, zi) = outline[i]
            (xj, zj) = outline[i + 1]
            ccw_up = ((xi - x0) * (zj - z0) - (xj - x0) * (zi - z0)) < 0
            if ccw_up:
                o.tri(top[0], top[i], top[i + 1], up)
                o.tri(bot[0], bot[i + 1], bot[i], down)
            else:
                o.tri(top[0], top[i + 1], top[i], up)
                o.tri(bot[0], bot[i], bot[i + 1], down)
    for i in range(len(outline)):
        j = (i + 1) % len(outline)
        (x0, z0), (x1, z1) = outline[i], outline[j]
        ex, ez = x1 - x0, z1 - z0
        ln = math.hypot(ex, ez) or 1.0
        n = o.normal(-ez / ln, 0, ex / ln)
        o.tri(top[i], bot[i], bot[j], n)
        o.tri(top[i], bot[j], top[j], n)


def ellipse_outline(cx, cz, rx, rz, steps):
    pts = []
    for i in range(steps):
        a = 2.0 * math.pi * i / steps
        pts.append((cx + math.sin(a) * rx, cz + math.cos(a) * rz))
    return pts


def box_outline(x0, z0, x1, z1):
    return [(x0, z1), (x1, z1), (x1, z0), (x0, z0)]


def spindle(o, cx, cz, half_len, radius, y_center, segs=10, taper=0.45):
    """A nacelle: a tapered tube lying along +Z, built as a ring of quads."""
    rings = []
    for k in range(segs + 1):
        t = k / segs
        z = cz - half_len + 2.0 * half_len * t
        # Fat in the middle, tapered at both ends, blunter at the front.
        shape = math.sin(math.pi * min(1.0, max(0.0, t))) ** 0.5
        r = radius * (taper + (1.0 - taper) * shape)
        ring = []
        for i in range(8):
            a = 2.0 * math.pi * i / 8
            ring.append(o.vert(cx + math.cos(a) * r, y_center + math.sin(a) * r, z))
        rings.append(ring)
    for k in range(segs):
        for i in range(8):
            j = (i + 1) % 8
            a = 2.0 * math.pi * (i + 0.5) / 8
            n = o.normal(math.cos(a), math.sin(a), 0)
            o.tri(rings[k][i], rings[k + 1][j], rings[k + 1][i], n)
            o.tri(rings[k][i], rings[k][j], rings[k + 1][j], n)


def hull_cruiser():
    """Federation inspired: a broad saucer forward, a slim neck, an engineering
    body aft, and two nacelles held out on pylons. Nose at +Z, deck at y=0.

    This is our own design in that tradition, not a copy of any published ship
    (CLAUDE.md section 10). Proportions are chosen so the six shield facings
    read clearly from directly above, which is the camera this game uses."""
    o = Obj()

    # Saucer, forward. Slightly egg shaped so the bow reads at a glance.
    extrude(o, ellipse_outline(0.0, 1.45, 1.55, 1.25, 24), 0.10, 0.46)
    # Bridge dome, a smaller disc on top of the saucer.
    extrude(o, ellipse_outline(0.0, 1.55, 0.42, 0.36, 12), 0.46, 0.62)
    # Neck down to the engineering body.
    extrude(o, box_outline(-0.34, -0.55, 0.34, 0.55), 0.06, 0.40)
    # Engineering body, aft, tapering to a stern shutter.
    extrude(o, [
        (-0.62, 0.30), (0.62, 0.30), (0.78, -0.90),
        (0.48, -2.05), (-0.48, -2.05), (-0.78, -0.90),
    ], 0.0, 0.50)
    # Pylons out to the nacelles.
    extrude(o, [(-1.02, -0.75), (-0.55, -0.55), (-0.55, -1.25), (-1.02, -1.45)], 0.14, 0.34)
    extrude(o, [(0.55, -0.55), (1.02, -0.75), (1.02, -1.45), (0.55, -1.25)], 0.14, 0.34)
    # Nacelles, running fore and aft outboard of the body.
    spindle(o, -1.32, -0.55, 1.35, 0.30, 0.30)
    spindle(o, 1.32, -0.55, 1.35, 0.30, 0.30)

    o.write("hull_cruiser.obj", "Federation inspired cruiser, saucer and two nacelles, nose at +Z")


def hull():
    # A chevron capital ship silhouette pointing +Z, with thickness so it
    # shades as a body rather than a sticker. Grey placeholder per the M1
    # scope: it is not an art milestone.
    #
    # The outline runs nose, starboard, tail, port so it winds the same way
    # as every other extruded outline. It is concave at the tail notch, but
    # extrude's fan from the nose vertex stays inside this particular shape.
    o = Obj()
    extrude(o, [
        (0.0, 3.0),      # nose
        (0.7, 0.6),      # stbd shoulder
        (2.0, -1.6),     # stbd wingtip
        (0.9, -1.2),     # stbd engine root
        (0.0, -1.9),     # tail notch
        (-0.9, -1.2),    # port engine root
        (-2.0, -1.6),    # port wingtip
        (-0.7, 0.6),     # port shoulder
    ], 0.0, 0.55)
    o.write("hull_placeholder.obj", "Placeholder capital ship hull, nose at +Z")


def main():
    # The raider hull is no longer written here: it became a painted, atlas
    # mapped ship in tools/gen_ship_raider.py, the same treatment the frigate
    # gets in tools/gen_ship_frigate.py.
    os.makedirs(OUT, exist_ok=True)
    hull_cruiser()
    wedge30()
    arc_segment()
    arc_glow()
    turn_arc()
    ring()
    quad()
    beam()
    hull()


if __name__ == "__main__":
    main()
