#!/usr/bin/env python3
# Generates the committed frigate: mesh, diffuse atlas, and emissive lights map.
#
# Style target is the author's own ship art in docs/examples/ship-art: a low
# poly hull, ONE small hand painted atlas rather than PBR maps, flat panels with
# hard black outlines, an off white hull with charcoal panelling and steel blue
# accents, and a separate mostly black lights map carrying only windows, strip
# lighting, and the deflector.
#
# Silhouette is a frigate in the Okinawa tradition: saucer forward and dominant,
# a short angular spine, a small engineering body, and two nacelles held high on
# swept pylons. See docs/12-ship-design-language.md. No geometry from any
# reference model is used, only its proportions.
#
# Per CLAUDE.md sections 2 and 3 this writes .obj and .png to disk. Run it and
# commit what it writes.
#
# Usage: python3 tools/gen_ship_frigate.py

import math
import os
import struct
import zlib

HERE = os.path.dirname(__file__)
MESH_OUT = os.path.join(HERE, "..", "assets", "meshes")
TEX_OUT = os.path.join(HERE, "..", "assets", "textures")

TEX = 256

# The palette, sampled from the author's Ship_1_finish atlas.
HULL_LIGHT = (222, 226, 230)
HULL_MID = (170, 178, 187)
HULL_DARK = (58, 66, 74)
PANEL = (38, 44, 52)
ACCENT = (108, 158, 178)
ACCENT_DEEP = (52, 96, 116)
RUST = (150, 66, 52)
OUTLINE = (12, 14, 18)

GLOW_WINDOW = (198, 232, 244)
GLOW_ENGINE = (120, 214, 208)
GLOW_MARK = (232, 150, 70)


# ---- mesh -------------------------------------------------------------------


class Obj:
    """OBJ writer with texture coordinates, so one atlas can paint the hull."""

    def __init__(self):
        self.v = []
        self.vt = []
        self.vn = []
        self.f = []

    def vert(self, x, y, z):
        self.v.append((x, y, z))
        return len(self.v)

    def uv(self, u, w):
        self.vt.append((u, w))
        return len(self.vt)

    def normal(self, x, y, z):
        self.vn.append((x, y, z))
        return len(self.vn)

    def tri(self, a, b, c, n, ta, tb, tc):
        self.f.append(((a, ta, n), (b, tb, n), (c, tc, n)))

    def write(self, name, comment):
        path = os.path.join(MESH_OUT, name)
        with open(path, "w") as f:
            f.write("# %s\n# Generated by tools/gen_ship_frigate.py. Edit the script.\n"
                    % comment)
            for v in self.v:
                f.write("v %.6f %.6f %.6f\n" % v)
            for t in self.vt:
                f.write("vt %.6f %.6f\n" % t)
            for n in self.vn:
                f.write("vn %.6f %.6f %.6f\n" % n)
            for face in self.f:
                f.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (
                    face[0][0], face[0][1], face[0][2],
                    face[1][0], face[1][1], face[1][2],
                    face[2][0], face[2][1], face[2][2]))
        print("wrote %s  (%d verts, %d tris)" % (name, len(self.v), len(self.f)))


def uv_in(o, rect, u, w):
    """Map 0..1 within an atlas rect given in pixels."""
    x0, y0, x1, y1 = rect
    return o.uv((x0 + (x1 - x0) * u) / TEX, 1.0 - (y0 + (y1 - y0) * w) / TEX)


def slab(o, outline, y0, y1, rect_top, rect_side):
    """Extrude an XZ polygon, planar mapping the caps into rect_top and the
    walls into rect_side. Outline is wound clockwise seen from above."""
    xs = [p[0] for p in outline]
    zs = [p[1] for p in outline]
    minx, maxx = min(xs), max(xs)
    minz, maxz = min(zs), max(zs)
    span_x = (maxx - minx) or 1.0
    span_z = (maxz - minz) or 1.0

    top, bot, tuv = [], [], []
    for (x, z) in outline:
        top.append(o.vert(x, y1, z))
        bot.append(o.vert(x, y0, z))
        tuv.append(uv_in(o, rect_top, (x - minx) / span_x, (z - minz) / span_z))

    up = o.normal(0, 1, 0)
    down = o.normal(0, -1, 0)
    for i in range(1, len(outline) - 1):
        o.tri(top[0], top[i + 1], top[i], up, tuv[0], tuv[i + 1], tuv[i])
        o.tri(bot[0], bot[i], bot[i + 1], down, tuv[0], tuv[i], tuv[i + 1])

    for i in range(len(outline)):
        j = (i + 1) % len(outline)
        (x0, z0), (x1, z1) = outline[i], outline[j]
        ex, ez = x1 - x0, z1 - z0
        ln = math.hypot(ex, ez) or 1.0
        n = o.normal(ez / ln, 0, -ex / ln)
        a = uv_in(o, rect_side, 0.0, 0.0)
        b = uv_in(o, rect_side, 1.0, 0.0)
        c = uv_in(o, rect_side, 1.0, 1.0)
        d = uv_in(o, rect_side, 0.0, 1.0)
        o.tri(top[i], bot[i], bot[j], n, d, a, b)
        o.tri(top[i], bot[j], top[j], n, d, b, c)


def disc_outline(cx, cz, rx, rz, steps):
    return [(cx + math.sin(2 * math.pi * i / steps) * rx,
             cz + math.cos(2 * math.pi * i / steps) * rz) for i in range(steps)]


def box(x0, z0, x1, z1):
    return [(x0, z1), (x1, z1), (x1, z0), (x0, z0)]


# Atlas rectangles, in pixels. Keeping them named makes the painter and the
# mapper agree without either guessing.
R_SAUCER = (8, 8, 120, 120)
R_SAUCER_RIM = (8, 124, 120, 140)
R_SPINE = (128, 8, 200, 72)
R_BODY = (128, 80, 200, 144)
R_NACELLE = (8, 148, 120, 196)
R_PYLON = (128, 152, 200, 196)
R_TRIM = (208, 8, 248, 248)


def build_mesh():
    o = Obj()
    # Saucer, forward and dominant: a frigate is mostly saucer.
    slab(o, disc_outline(0.0, 1.55, 1.32, 1.12, 16), 0.10, 0.42, R_SAUCER, R_SAUCER_RIM)
    # Bridge blister.
    slab(o, disc_outline(0.0, 1.62, 0.30, 0.26, 8), 0.42, 0.56, R_TRIM, R_TRIM)
    # Angular spine running aft, narrowing.
    slab(o, [(-0.34, 0.62), (0.34, 0.62), (0.24, -1.20), (-0.24, -1.20)],
         0.14, 0.38, R_SPINE, R_SPINE)
    # Small engineering body with a cut stern.
    slab(o, [(-0.46, -0.60), (0.46, -0.60), (0.38, -1.72), (-0.38, -1.72)],
         0.02, 0.44, R_BODY, R_BODY)
    # Pylons, swept back and rising outboard.
    slab(o, [(-0.44, -0.55), (-0.30, -0.72), (-1.02, -1.30), (-1.16, -1.10)],
         0.30, 0.46, R_PYLON, R_PYLON)
    slab(o, [(0.30, -0.72), (0.44, -0.55), (1.16, -1.10), (1.02, -1.30)],
         0.30, 0.46, R_PYLON, R_PYLON)
    # Nacelles: long, flat sided, blunt in front, sitting above the deck.
    for side in (-1.0, 1.0):
        cx = 1.12 * side
        slab(o, [(cx - 0.17, 0.72), (cx + 0.17, 0.72),
                 (cx + 0.21, -1.62), (cx - 0.21, -1.62)],
             0.46, 0.74, R_NACELLE, R_NACELLE)
    o.write("hull_frigate.obj", "Okinawa inspired frigate, nose at +Z, atlas mapped")


# ---- texture ----------------------------------------------------------------


class Paint:
    """A tiny RGBA painter: flat fills with hard outlines, which is what the
    reference art does. No gradients and no anti aliasing, deliberately."""

    def __init__(self, size):
        self.size = size
        self.px = [(0, 0, 0, 0)] * (size * size)

    def put(self, x, y, rgba):
        if 0 <= x < self.size and 0 <= y < self.size:
            self.px[y * self.size + x] = rgba

    def rect(self, x0, y0, x1, y1, rgb, outline=OUTLINE):
        for y in range(int(y0), int(y1)):
            for x in range(int(x0), int(x1)):
                edge = (x in (int(x0), int(x1) - 1) or y in (int(y0), int(y1) - 1))
                self.put(x, y, (outline + (255,)) if (edge and outline) else rgb + (255,))

    def band(self, x0, y0, x1, y1, rgb):
        for y in range(int(y0), int(y1)):
            for x in range(int(x0), int(x1)):
                self.put(x, y, rgb + (255,))

    def dots(self, x0, y0, count, step, rgb, vertical=False):
        for i in range(count):
            x = x0 + (0 if vertical else i * step)
            y = y0 + (i * step if vertical else 0)
            self.put(int(x), int(y), rgb + (255,))
            self.put(int(x) + 1, int(y), rgb + (255,))

    def save(self, path):
        rows = []
        for y in range(self.size):
            row = bytearray([0])
            for x in range(self.size):
                row += bytes(self.px[y * self.size + x])
            rows.append(bytes(row))
        raw = b"".join(rows)

        def chunk(tag, data):
            return (struct.pack(">I", len(data)) + tag + data
                    + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

        png = (b"\x89PNG\r\n\x1a\n"
               + chunk(b"IHDR", struct.pack(">IIBBBBB", self.size, self.size, 8, 6, 0, 0, 0))
               + chunk(b"IDAT", zlib.compress(raw, 9))
               + chunk(b"IEND", b""))
        with open(path, "wb") as f:
            f.write(png)
        print("wrote %s" % os.path.basename(path))


def paint_diffuse():
    p = Paint(TEX)

    # Saucer: light hull, a darker inner ring, and radial panel seams.
    x0, y0, x1, y1 = R_SAUCER
    p.rect(x0, y0, x1, y1, HULL_LIGHT)
    p.rect(x0 + 14, y0 + 14, x1 - 14, y1 - 14, HULL_MID)
    p.rect(x0 + 38, y0 + 38, x1 - 38, y1 - 38, HULL_DARK)
    p.rect(x0 + 50, y0 + 50, x1 - 50, y1 - 50, ACCENT_DEEP)
    for i in range(6):
        p.band(x0 + 8 + i * 18, y0 + 6, x0 + 9 + i * 18, y1 - 6, OUTLINE)
    p.rect(*R_SAUCER_RIM, HULL_MID)
    p.band(R_SAUCER_RIM[0], R_SAUCER_RIM[1] + 7, R_SAUCER_RIM[2],
           R_SAUCER_RIM[1] + 9, ACCENT)

    # Spine and body: charcoal panelling with steel blue service strips.
    p.rect(*R_SPINE, PANEL)
    p.band(R_SPINE[0] + 10, R_SPINE[1] + 8, R_SPINE[0] + 18, R_SPINE[3] - 8, ACCENT_DEEP)
    p.band(R_SPINE[2] - 18, R_SPINE[1] + 8, R_SPINE[2] - 10, R_SPINE[3] - 8, ACCENT_DEEP)
    p.rect(*R_BODY, HULL_DARK)
    p.rect(R_BODY[0] + 12, R_BODY[1] + 12, R_BODY[2] - 12, R_BODY[3] - 26, PANEL)
    p.band(R_BODY[0] + 6, R_BODY[3] - 18, R_BODY[2] - 6, R_BODY[3] - 10, RUST)

    # Nacelles: light shell, deep accent grille down the middle.
    p.rect(*R_NACELLE, HULL_LIGHT)
    p.band(R_NACELLE[0] + 6, R_NACELLE[1] + 16, R_NACELLE[2] - 6,
           R_NACELLE[1] + 32, ACCENT_DEEP)
    p.band(R_NACELLE[0] + 6, R_NACELLE[1] + 20, R_NACELLE[2] - 6,
           R_NACELLE[1] + 28, ACCENT)
    p.rect(R_NACELLE[0], R_NACELLE[3] - 10, R_NACELLE[2], R_NACELLE[3], HULL_DARK)

    # Pylons and a trim block for the small parts.
    p.rect(*R_PYLON, HULL_MID)
    p.band(R_PYLON[0] + 8, R_PYLON[1] + 10, R_PYLON[2] - 8, R_PYLON[1] + 14, PANEL)
    p.rect(*R_TRIM, HULL_MID)
    p.rect(R_TRIM[0] + 6, R_TRIM[1] + 6, R_TRIM[2] - 6, R_TRIM[1] + 40, ACCENT_DEEP)
    p.rect(R_TRIM[0] + 6, R_TRIM[1] + 48, R_TRIM[2] - 6, R_TRIM[1] + 84, RUST)

    p.save(os.path.join(TEX_OUT, "hull_frigate_diffuse.png"))


def paint_lights():
    """Mostly black, like the reference lights map: only windows, strip
    lighting, the deflector, and the drive glow are lit."""
    p = Paint(TEX)
    p.band(0, 0, TEX, TEX, (0, 0, 0))

    # Saucer windows in two arcs, and the deflector as a bright disc.
    for i in range(10):
        p.dots(R_SAUCER[0] + 16 + i * 9, R_SAUCER[1] + 26, 1, 0, GLOW_WINDOW)
        p.dots(R_SAUCER[0] + 16 + i * 9, R_SAUCER[3] - 28, 1, 0, GLOW_WINDOW)
    p.rect(R_SAUCER[0] + 48, R_SAUCER[1] + 48, R_SAUCER[0] + 64,
           R_SAUCER[1] + 64, GLOW_ENGINE, outline=None)

    # Spine service lights, engineering marker, nacelle grille.
    p.dots(R_SPINE[0] + 14, R_SPINE[1] + 14, 8, 6, GLOW_WINDOW, vertical=True)
    p.dots(R_BODY[0] + 18, R_BODY[1] + 20, 5, 8, GLOW_MARK, vertical=True)
    p.band(R_NACELLE[0] + 8, R_NACELLE[1] + 21, R_NACELLE[2] - 8,
           R_NACELLE[1] + 27, GLOW_ENGINE)
    p.band(R_NACELLE[0] + 8, R_NACELLE[3] - 8, R_NACELLE[2] - 8,
           R_NACELLE[3] - 4, GLOW_MARK)

    p.save(os.path.join(TEX_OUT, "hull_frigate_lights.png"))


def main():
    os.makedirs(MESH_OUT, exist_ok=True)
    os.makedirs(TEX_OUT, exist_ok=True)
    build_mesh()
    paint_diffuse()
    paint_lights()


if __name__ == "__main__":
    main()
